kind: pipeline
name: default
type: exec

steps:
  - name: pr checks
    commands:
      - echo "pr checks from"
      - sh cmd.sh
    when:
      branch:
        - release/*
        - main
        - develop
      event:
        - pull_request

trigger:
  branch:
    - main
    - develop
    - release/*
  event:
    - push
    - pull_request
